name: Update project licenses

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Install license processing tools
      run: |
        cargo install cargo-about
        sudo apt install html2text
    - name: Update licensing notes
      run: |
        cargo about generate about.hbs > LICENSE.html
        html2text -width 88 -style compact -nobs -utf8 -o LICENSE.txt LICENSE.html
    - name: Commit changes
      uses: EndBug/add-and-commit@v8
      with:
        # Git message
        message: Automated update to license notices
